= Music
Kerem Bozdas
:idprefix:
:idseparator: -
:page-pagination:
:description: Sharing the music I have discovered

Random music discoveries.

== Tommy Richman - MILLION DOLLAR BABY (2025-09-02)

video::Zf1d8SGuxfs[youtube,width=640,height=480]

== Eumir Deodato - Os Grilos (2025-05-27)

video::T4pPo7IJKhM[youtube,width=640,height=480]

== Jiro Inagaki & Soul Media - Funky Stuff (2025-05-21)

> This album helped me solve a tricky case in downtown L.A in 1975.

video::kjxxVkSd0XA[youtube,width=640,height=480]

== Juna Serita - Pain or Pleasure? (2025-05-13)

video::6L4TbjEIaaY[youtube,width=640,height=480]

== Star-Lord Band - Ghost (2025-04-10)

video::jLfePHz-xIw[youtube,width=640,height=480]

== Anri - Anri in Concert (2025-01-13)

Live Anri concert footage from 1984.

video::aSnmeUmPlIs[youtube,width=640,height=480]

== Deep Forest - Elemental (2024-12-13)

video::-92VNtBPCLY[youtube,width=640,height=480]

== Yasuaki Shimizu - Umi No Ue Kara (2024-12-01)

video::Lk0UPubyL28[youtube,width=640,height=480]

== Yuji Toriyama - Lumberjack (2024-11-29)

video::RdAd_m3TWf8[youtube,width=640,height=480]

== TOPS - Petals (2024-11-10)

[verse]
No one to call, not much to say
All I want to do
Let the petals fall away

video::vJ7jg9ECWXE[youtube,width=640,height=480]

== Guthrie Govan - Waves (2024-03-05)

video::fSbUGufOt8o[youtube,width=640,height=480]

== Plini - Impulse Voices (2024-02-19)

Best thing I've discovered in 2024 so far.

video::NdSMeBrNp4A[youtube,width=640,height=480]

== Farya Faraji - Zaman (2023-08-06)

video::zg8dgqBS6aA[youtube,start=2790,end=3030,width=640,height=480]

== RAYE - NPR Tiny Desk Concert (2023-07-02)

video::DL1zyUjzwno[youtube,width=640,height=480]

== Erkan Oğur - Double Trouble (2023-05-24)

video::7mWffx102bI[youtube,width=640,height=480]

== Depeche Mode - Enjoy the Silence (2023-05-01)

video::G8ZEIhBVQQc[youtube,width=640,height=480]

== Pool Villa - Seaside (2023-04-19)

video::pGw9debfWgw[youtube,width=640,height=480]

== Vanilla - Dreams (2023-04-19)

[verse]
So, here's to life
And every joy it brings
To dreamers and their dreams

video::ECGNfM8LOLY[youtube,width=640,height=480]

== Carl Winther - Moonlight in Vermont (2023-04-04)

[verse]
notes flow freely
like blood pulsating from within
giving you a sense of calm
relaxing yet stimulating

video::BB1NUEvSEgg[youtube,width=640,height=480]

== Priscilla Ahn - The Boobs Song (2023-03-31)

I have a soft spot for the kazoo.

video::DW5ggG-GGmw[youtube,width=640,height=480]

== Allan Taylor - Colour to the Moon (2023-03-24)

video::EFo2wvQEm_s[youtube,width=640,height=480]

== The Universe Smiles Upon You (2023-03-14)

I've been playing this on repeat lately.

video::NLshfP9xmHc[youtube,width=640,height=480]

== Khruangbin (2023-03-06)

=== NPR Music Tiny Desk Concert
video::vWLJeqLPfSU[youtube,width=640,height=480]

.Hilarious comments on the drummer's impeccable timing
[%collapsible]
====
* The drummer tells the sun exactly when to rise every morning.
* The legend says that just after giving birth to the drummer his mother asked him what time it was.
* The reason why everything is so perfectly synced is because the drummer is a high level telepath controlling the guitarist and bass player who are just vessels for his will.
* Time is second-guessing itself when listening to this drummer's impeccable timing.
* I heard this drummer got lost in the wilderness with no phone or watch and when they found him 3 years later he knew what second it was.
* I came back three years later and the drummer is still on time!
* Drummer's so on point he cured my arrhythmia.
* There are three certainties in life. Death, taxes, and the drummer not missing a beat.
* This drummer has never been in the wrong place at the wrong time.
* That drummer does not keep time. He is time.
* https://youtu.be/vWLJeqLPfSU?t=337[5:29] drummer clicks twice to signal upcoming bridge so everyone stays on time.
* The drummer kept time so well that we as a society realized we no longer need daylight savings.
* Fun fact: The drummer is the creator, publisher, chief writer, columnist, editor, regional manager, and head of distribution of Time Magazine.
* Drummer adjusts half a beat after every 5 millionth beat to compensate for earth's equinox tilt.
* The drummer is the type of guy who pays his bills on time.
====

=== Khruangbin @ Villain | Pitchfork Live

video::q4xKvHANqjk[youtube,width=640,height=480]

=== Donald "DJ" Johnson Interviews

* https://www.drumeo.com/beat/donald-dj-johnson-interview-drumeo-gab-podcast-199/[Donald "DJ" Johnson: Metronome Madness!]
* https://www.podcastone.com/episode/Episode-2-Khruangbins-DJ-Johnson-Evans-UV-Series-Drumheads-and-More[The Modern Drummer Podcast Episode 2: Khruangbin's DJ Johnson, Evans UV Series Drumheads, and More]
* https://web.archive.org/web/20200725065553/https://www.moderndrummer.com/article/khruangbins-dj-johnson/[Modern Drummer features Khruangbin’s DJ Johnson]

