name: Update stars
on:
  workflow_dispatch:
  schedule:
  - cron: 5 8 * * 0
jobs:
  update-stars:
    name: Update stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/krmbzds/starred.git#egg=starred
    - name: Update repository
      env:
        GITHUB_TOKEN: ${{ secrets.STARRED_TOKEN }}
      run: starred --username krmbzds --repository lists --sort --token ${GITHUB_TOKEN} --message 'Update stars'

